<?php
/**
 * REDCap External Module: Record Autonumber
 * Specify record auto-numbering rules e.g. including part of DAG name
 * @author Luke Stevens, Murdoch Children's Research Institute
 */
namespace MCRI\RecordAutonumber;

/**
 * AbstractAutonumberGenerator
 *
 * @author luke.stevens
 */
abstract class AbstractAutonumberGenerator {
        protected $config;

        public function __construct($config) {
                try {
                        $this->config = $config;
                        $this->validateConfiguration();
                } catch (RecordAutonumberException $ex) {
                        throw new AutonumberConfigException('Module configuration error for AutonumberGenerator option '.static::getClassNameWithoutNamespace().': "'.$ex->getMessage().'"', 0, $ex);
                }
        }
        
        /**
         * Validate any additional configuration parameters entered in module 
         * configuration
         * Throw an exception if some problem identified.
         */
        abstract protected function validateConfiguration();
        
        /**
         * Generate the next record id according to the desired logic/pattern
         * @return string The next record id 
         */
        abstract public function getNextRecordId($params=null);
        
        /**
         * Check whether the supplied id value matches the format expected for
         * an id generated by this class
         * @param string id to check
         * @return bool 
         */
        abstract public function idMatchesExpectedPattern($id);
        
        /**
         * Require selection of DAG for new records?
         * @return boolean
         */
        public function requireDAG() {
                return false;
        }
        
        /**
         * Return array of field names that are required for generating the 
         * record id.
         * E.g. array('__GROUPID__','diagnosis')
         * @return array
         */
        public function getRequiredDataEntryFields() {
                return array();
        }        
        
        private static function getClassNameWithoutNamespace() {
                $classname = get_called_class();
                if ($pos = strrpos($classname, '\\')) {
                        return substr($classname, $pos + 1);
                }
                return $classname;
        }
}
